name: fred-et-al
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- python=3.6
- jupyter
- notebook
- tqdm
- scipy=1.4
- tensorflow=1.5
- pip
- pip:
  - Theano==0.6
  - Pillow
  - matplotlib

